### ISSUE TITLE
Updates needed for pds.nasa.gov lift-and-shift

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#198]
Timeline for cutover.

- [x] 12/6 - Action 1a: Complete today's data release (@rchenatjpl)
   * Track which files are updated
   * Notifies all that release has been completed
   * WEBSITE CONTENT UPDATE FREEZE

- [x] 12/6 - Action 1b: Setup hourly sync of pds-prod1, pds-gamma, pds-engineering to AWS (SA Team)

- [x] 12/6 - Action 2: Add Richard's Updates to Github (@c-suh / @viviant100 )
   - [x] Copy latest versions of those files from Richard's updates to Github
 
- [x] 12/7 - Action 3: Test out using github instead of subversion for website (@c-suh / @acyu-jpl )
   - [x] Backup existing htdocs on pds-gamma: (e.g. mv htdocs htdocs.bk.20211206)
   - [x] Execute procedure on pds-gamma to test out new website deployment: https://wiki.jpl.nasa.gov/display/PDSEN/Website+Deployment+Procedure .
   - [x] Review website and make necessary updates to procedure to ensure sync with previous pds-gamma website
      * Password updates to data-search
      * .htaccess updates
      * Clones of numerous dependency repos (feedback-widget, pds-app-bar, etc.)
      * Others?

- [x] 12/7-12/8 - Action 4: Perform same website deployment procedure on pds-prod1 (@c-suh / @acyu-jpl )

- [x] 12/8 - Action 5: Update Ops/Data Engineering procedures to use git commands (Catherine/Allan/Richard)

- [x] 12/8 - Action 6: Website Content Update Freeze Complete (All): obsolete, the on-prem and AWS site are mirrored hourly on 2 directories. Beware of application updates (e.g. doi-ui, doi-service).

- [x] 12/8-12/10 - Action 7a: Complete B12.0 website updates / LDD deployment (@c-suh / @acyu-jpl ) (https://github.com/NASA-PDS/operations/issues/197)

- [x] 12/8-12/10 - Action 7b: AGU web page development (@c-suh / @acyu-jpl ) (https://github.com/NASA-PDS/portal-tasks/issues/4)

- [x] 1/31 - Action 8: Test all applications and functionality of AWS sites (list of tickets [here](https://github.com/NASA-PDS/operations/issues/198#issuecomment-1021644404))
 
- [x] 12/16 - Action 9: Final OK to switchover pds.nasa.gov/pds-gamma to AWS (@viviant100 / @jordanpadams )

- [x] 12/20 - Action 10: Initiate DNS switchover pds.nasa.gov, pds-gamma.jpl.nasa.gov, pds-engineering.jpl.nasa.gov to AWS (SA Team)

- [x] Once DNS cutover completes - 
   - [x] Action 10a: All website, operations, and data engineering tasks move to AWS resources (Ops/Richard)
   - [x] Action 10b: Discontinue on-prem to AWS sync (SA Team)

- [ ] clarify where the documentation of deployment of application is or should be (e.g. doi-service...), see https://wiki.jpl.nasa.gov/display/PDSEN/Software+Installation+and+Deployment+Guides

**Comment by rchenatjpl** [comment]
@viviant100 @acyu-jpl @jordanpadams 
OK, today's release is out with help from @c-suh. Next scheduled release is 12/15

**Comment by c-suh** [comment]
@viviant100, I cross-checked the files from the latest svn updates with the files in the new repo and [pushed](https://github.com/NASA-PDS/portal-legacy/commit/ce37465a8574ef83b38f7d73ba2cd0119cac3c74) the difference. Do you have anything more for Action 2? If not, that is complete.

**Comment by viviant100** [comment]
Consider action 2 done! Thanks @c-suh.

**Comment by viviant100** [comment]
Thanks for wrapping up 12/6 data release @rchenatjpl.  Starting next data release, we'll be using Github in lieu of svn for the updates.  Feel free to reach out for any questions.

**Comment by c-suh** [comment]
@jordanpadams and @viviant100, the one-time sync for the `/data` directory (this is NOT static web content nor covered by the hourly sync in Action 1b) has been done thanks to Andrew, but I think there's active development happening (e.g. directory added this morning not caught by the sync: https://pds.nasa.gov/data/pds4/test-data/registry/lab.hydrocarbon_spectraV1/). So, I think a freeze on the `/data` directory would be in order with a final one-time sync right before the cutover. Would this be a new Action item right before the second Action 5 on 12/16 ?

**Comment by jordanpadams** [comment]
@c-suh since we are pushing the cutover for a few weeks, I would recommend we setup a sync for an hourly sync for the data, similar to the website, and then we can work on a freeze and shutdown of the sync once we are ready for the cutover.

**Comment by c-suh** [comment]
@jordanpadams and @viviant100, just verifying that Action 4 is for prod2 as well?

Note: Action 3 has been completed. Please give prem gamma a try and let me know if you find anything missing or broken.

**Comment by viviant100** [comment]
@c-suh Action 4 applies to prod2 as well.

**Comment by c-suh** [comment]
@acyu-jpl has reviewed the deployment procedure and is ready to run it for prod1 and prod2 tomorrow.

**Comment by acyu-jpl** [comment]
@c-suh Action 4 has been applied to pds-prod1.  [pds-prod1](https://pds-prod1.jpl.nasa.gov/) is loading correctly, with tophat & feedback widget showing as well.

**Comment by acyu-jpl** [comment]
Action 4 has been applied to (pds-prod2)[https://pds-prod2.jpl.nasa.gov). pds-prod2 is loading correctly, with tophat & feedback widget showing as well.

**Comment by acyu-jpl** [comment]
Quick test reveal that the Java app is not working correctly on pds-prod1 or pds-prod2 or pds-gamma
the keyword search app https://pds-gamma.jpl.nasa.gov/datasearch/keyword-search/
and the dataset status app https://pds.nasa.gov/datasearch/ds-status/

**Comment by c-suh** [comment]
@acyu-jpl let's first replace htdocs on prod2 with the backup htdocs, then test on prod1.
Additionally, is this the same for you - Data Search at https://pds.nasa.gov/datasearch/data-search/ works on gamma but not on prod1/2?

**Comment by acyu-jpl** [comment]
@c-suh I restored the pre-git htdocs on pds-prod2.  However, Keyword Search and Data Set Status are still broken.  The data search is working on all environment.

**Comment by c-suh** [comment]
@acyu-jpl OK; thank you. I will take a look now.

**Comment by c-suh** [comment]
Created a [ticket with the SAs](https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1041). Just discovered that pages from Data Set Status are also 404 across all prem machines, e.g. https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Aapollo_seismic_event_catalog&version=1.0. Looking into that now..

**Comment by c-suh** [comment]
@acyu-jpl Data Search was not working because I had mixed up part of the process. I've tested it on pds-prod1 and updated the documentation. Please apply [this section](https://wiki.jpl.nasa.gov/display/PDSEN/Website+Deployment+Procedure#WebsiteDeploymentProcedure-PasswordUpdates) to the git-htdocs directory on pds-prod2 and make that directory operational.

**Comment by c-suh** [comment]
@acyu-jpl after switching prod2 back to git, also do a `git pull`. Thank you

**Comment by acyu-jpl** [comment]
@c-suh pds-prod2 has switch back to the git working copy.  ran `git pull origin main`, no conflict detected
![image](https://user-images.githubusercontent.com/68704695/145477917-080659b5-42c3-4a7b-a209-2678a453797c.png)

**Comment by c-suh** [comment]
**Action 5:** I've started updating documentation, but there are many procedures. @rchenatjpl and @acyu-jpl, please update those processes for which you are responsible and let me know if you come across any which I might have missed.

**Action 7a:** https://github.com/NASA-PDS/operations/issues/197#issuecomment-990537849

**Action 7b:** talked with @acyu-jpl and this seems straightforward enough that I've asked him to look into misc application problems while I work this agu page.

**Comment by c-suh** [comment]
@acyu-jpl , I see that prod2 is using git (thank you), but **step 4** of the [updated documentation](https://wiki.jpl.nasa.gov/display/PDSEN/Website+Deployment+Procedure#WebsiteDeploymentProcedure-PasswordUpdates) has not been applied. Please do only that one step (not any of the other steps) then leave the changes (how those are to be handled are TBD and are fine to stay as untracked changes until then).

**Comment by acyu-jpl** [comment]
@c-suh I updated the password manually on pds-prod2 for the following 4 files based on the **step 4** of the [documentation](https://wiki.jpl.nasa.gov/pages/viewpage.action?spaceKey=PDSEN&title=Website+Deployment+Procedure)
datasearch/data-search/getInvestigation.php
datasearch/data-search/getInvestigations.php
datasearch/data-search/getTarget.php
datasearch/data-search/getTargets.php

However, I do suggest that we ask SA to setup environment variables for the connection information so we can commit these 4 files to git, and not expose connection credential

**Comment by jordanpadams** [comment]
@acyu-jpl @c-suh maybe let's create a separate ticket to track that since it is isn't required right now?

but i 100% agree. this will avoid an unintentional commit that will expose the info

**Comment by c-suh** [comment]
Belatedly added Action 8 to test all applications/functionality of the AWS sites. Direct message me for the document tracking the tests.

**Comment by tloubrieu-jpl** [comment]
A follow up ticket has been created for the documentation https://github.com/NASA-PDS/portal-tasks/issues/23, this current ticket is now closed
