### ISSUE TITLE
remove Wave LDD

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#242]
## 💡 Description
(Re)move Wave LDD from active to in-development. Requested by Joe Mafi via email.

Note: this has an LDD posted [here](https://pds.nasa.gov/datastandards/dictionaries/index-pre-1.15.0.0.shtml#wave), but this is okay to remove because it is a clone of the original Particles LDD, out of date, superseded, and never used.

### To-Dos
- [x] remove from all Data Dictionary pages
- [x] ~~remove from Operations' config.yml~~ make sure it's in correct development category so that script skips it
- [x] request Steve to move it to "Held for Future Use" in the PDS Namespace Registry
-  ~~(TBD) delete [Wave LDD repo](https://github.com/pds-data-dictionaries/ldd-wave)~~

**Comment by tloubrieu-jpl** [comment]
This LDD can be considered in development so that it does not show up.

**Comment by c-suh** [comment]
LDDs are removed from all data dictionary pages, and the operations script has been updated. Just waiting to hear from Steve about its placement in the namespace registry.
