### ISSUE TITLE
Test staging server with new OL8 OS Version

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/operations#395]
## 💡 Description
Verify new staging 
- [x] (1) Github
    - [x] Website Updates
- [x] (2) PDS services 
    - [x] DOI service
    - [x] Registry
    - [x] Harvest
    - [x] Registry, Legacy
    - [x] Harvest, Legacy
    - [x] Validate
- [ ] (3) Browser (Tool/applications through the interfaces)
   - [x] Data Search
   - [x] Keyword Search
   - [x] Data Set Status
   - [x] Tool Registry
   - [x] Data Dictionary Search
   - [x] DOI Search
   - [x] Subscription Service
   - [x] Release Manager
   - [x] Resource Manager
   - [x] Catalog Manager
   - [ ] UCD Tools
- [x] (4) Cron jobs
- [x] (5) Authentication 

Procedures:
- [x] NSSDCA
- [x] Build release

### Sub-tasks
- https://github.com/NASA-PDS/registry-legacy-solr/issues/93
- https://github.com/NASA-PDS/ds-view/issues/22
- https://github.com/NASA-PDS/operations/issues/431
- https://github.com/NASA-PDS/operations/issues/435
- https://github.com/NASA-PDS/operations/issues/430
- https://github.com/NASA-PDS/operations/issues/429
- https://github.com/NASA-PDS/operations/issues/428
- https://github.com/NASA-PDS/operations/issues/432
- https://github.com/NASA-PDS/operations/issues/496
- https://github.com/NASA-PDS/operations/issues/497
- https://github.com/NASA-PDS/operations/issues/433

**Comment by tloubrieu-jpl** [comment]
Some issues, @c-suh is interacting with the SAs.

**Comment by c-suh** [comment]
SAs and I are working parallel items for this ticket.

**Comment by c-suh** [comment]
Multiple updates from the SAs. Must discuss an application with Thomas at next breakout.

**Comment by c-suh** [comment]
SA ticket [here](https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-4041).

**Comment by tloubrieu-jpl** [comment]
SAs are still working on it.

**Comment by c-suh** [comment]
- databases are TBD
- I will take a look at ucd-tools this week
- md5/FIPs error is no longer erroring

**Comment by c-suh** [comment]
- databases are still not connected
- left a couple questions regarding ucd-tools for the SAs. In the meantime, am trying to set up mvn so as to be able to build this application if needed
- md5/FIPs error is back and I need to look into this

**Comment by tloubrieu-jpl** [comment]
Catherine need to redeploy some java applications.

**Comment by c-suh** [comment]
Got a jar from the SA. It's unclear if this is required for multiple applications, but I will look into that after getting mvn set up correctly to be able to build these applications.

**Comment by c-suh** [comment]
I have maven and java and other aspects set up such that the application is finally building. However, deployment has errors. I've reached out to the SA with questions.

**Comment by c-suh** [comment]
Am in communication with the SA and Richard about a variety of issues:
- harvest and java
- applications and java
- ucd
- coldfusion

**Comment by acyu** [comment]
I had tested the following 3 applications on  https://pdscloud-gamma-ol8-lb-2038894419.us-west-2.elb.amazonaws.com/ and they are working as expected

subscription service
release manager
catalog manager

**Comment by tloubrieu-jpl** [comment]
See for details https://docs.google.com/spreadsheets/d/152V38MQh6iuP0s7u7ozweAColbQGZ3-TkwrPgJOneiI/edit?usp=drive_web&ouid=114680991820234785180

**Comment by c-suh** [comment]
Catching up with various tickets and notes. In the meantime, re-initial testing:
- Data Search: php 500
- Keyword Search: 503
- Data Set Status: no results. Likely something to do with the database
- Tool Registry: 503 and Uncaught SyntaxError: Unexpected token '<'
- Data Dictionary Search: 503 and Uncaught SyntaxError: Unexpected token '<'
- DOI Search: returns results
- Subscription Service: Error Executing Database Query: null, message from server: "Host '10.100.3.204' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
- Release Manager: Error Executing Database Query: null, message from server: "Host '10.100.3.204' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
- Resource Manager: database connection failed
- Catalog Manager: Error Executing Database Query: null, message from server: "Host '10.100.3.204' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
- DOI Editor: 403 Forbidden

**Comment by tloubrieu-jpl** [comment]
@c-suh is exchanging with the SA on the database issue and will do more testing.

**Comment by tloubrieu-jpl** [comment]
The SA in charge is out sick.

**Comment by c-suh** [comment]
- Data Search: (same as before) php 500
- Keyword Search: works!
- Data Set Status: (same as before) no results
- Tool Registry: Uncaught SyntaxError: Unexpected token ':'
- Data Dictionary Search: Uncaught SyntaxError: Unexpected token ':'
- DOI Search: (same as before) returns results
- Subscription Service: (same as before) Error Executing Database Query: null, message from server: "Host '10.100.3.204' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
- Release Manager: (same as before) Error Executing Database Query: null, message from server: "Host '10.100.3.204' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
- Resource Manager: (same as before) database connection failed
- Catalog Manager: (same as before) Error Executing Database Query: null, message from server: "Host '10.100.3.204' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
- DOI Editor: (same as before) 403 Forbidden

---
checked in with SA yesterday about database question. He will get back to me.

**Comment by c-suh** [comment]
Database issue again and have asked the SA about it.

**Comment by tloubrieu-jpl** [comment]
Database issue is fixed by the SAs (too many connexion error).

**Comment by jordanpadams** [comment]
@c-suh 
> Tool Registry: Uncaught SyntaxError: Unexpected token ':'
> Data Dictionary Search: Uncaught SyntaxError: Unexpected token ':'

FYI, these all are supposed to query the new Solr, so we will need to modify them to query the new API. TBD on this until we actually get it working.

**Comment by jordanpadams** [comment]
We should probably just create separate tickets for addressing those. For the things that are not working, let's create individual tickets for those.

**Comment by c-suh** [comment]
Resuming testing of the checklisted items and starting review of the linked subtasks. A note that there is no exiting gamma to compare this one to.

**Comment by c-suh** [comment]
Similar status - reviewing and testing these items.

**Comment by c-suh** [comment]
Doing basic testing and checking for documentation. Plan to wrap this up this week.

**Comment by c-suh** [comment]
Applications that do not work as intended:
- **Data Search:** 500
- **Data Set Status:** Node Name Not Found
- **Resource Manager:** database connection failed
- **DOI Editor:** Forbidden

---

NOTES:
- Unsure how to test search-index
- Harvest and Registry components, both current and legacy, were tested by seeing if incomplete commands were recognized, not by seeing of processes fully ran correctly to completion.

**Comment by c-suh** [comment]
Will check in next week about closing this parent ticket.

**Comment by c-suh** [comment]
Missing cronjob for google sitemap needs to be reimplemented.

**Comment by c-suh** [comment]
Plan is to wrap up all problem items as best as we can by this week and next week, begin upgrade of other machines.

**Comment by jordanpadams** [comment]
Only thing left is UCD tools, which we are iceboxing
