### ISSUE TITLE
B14.0 EN Deployment & Release

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#455]
## 💡 Description

Tue 11/21/23 - Fri 12/1/23
- [x] Discipline LDD Release @csuh
     - [x] Stage (internal wiki, dLDDReleaseProcedures-StageLDDRelease)
     - [x] Release (internal wiki, dLDDReleaseProcedures-ReleaseLDDs)
     - [x] Post Release (internal wiki, dLDDReleaseProcedures-PostReleaseUpdates) 
- [x] Deployment of Test Environment
    - [x] DOI Service @csuh
    - [x] DOI UI @csuh
    - [x] Registry
        - [x] API @tloubrieu-jpl / @sjoshi-jpl
        - [x] update API documentation @tloubrieu-jpl / @sjoshi-jpl
        - [x] Registry Sweeper @tloubrieu-jpl / @sjoshi-jpl
        - [x] Registry Manager @c-suh 
        - [x] Standalone Harvest @csuh
- [x] Deployment of Operational Environment
    - [x] DOI Service @csuh
    - [x] DOI UI @csuh
    - [x] Registry
        - [x] API @tloubrieu-jpl / @sjoshi-jpl
        - [x] update API documentation @tloubrieu-jpl / @sjoshi-jpl
        - [x] Registry Sweeper @tloubrieu-jpl / @sjoshi-jpl
        - [x] Registry Manager @c-suh 
        - [x] Standalone Harvest @csuh

- [x] Webpage Updated @csuh
    - [x] Include updates to all pages that list PDS4 Build Schedule to add 4 additional releases (e.g. [here](https://pds.nasa.gov/datastandards/about/))
    - [x] Update multiple pages for new documents
    - [x] Post and update symlink for WebHelp ALL after Steve generates and sends those files
- [x] Released to the Public

**Comment by c-suh** [comment]
Had a number of issues with the virtual environment. Finally created a working environment with compatible python version to packages required, updated the script for moved imports, and asked the SAs to create a missing directory. Currently blocked until that's created but will shift to [this new task](https://github.com/NASA-PDS/operations/issues/466) in the meantime.

**Comment by c-suh** [comment]
Unsure about configuring Standalone Harvest according to https://nasa-pds.github.io/registry/user/harvest_job_configuration.html#registry-integration. What file is this for?

**Comment by c-suh** [comment]
@viviant100 and @tloubrieu-jpl, other than Harvest's configuration (comment just above) and some issues for DOI Service on gamma (as expected, per the conversation last breakout), all my items are done!

**Comment by viviant100** [comment]
> The SAs created the directory, but running the script ran into another error, for which I opened the ticket mentioned just above, in which Jordan pointed me to another repository. Making the changes.

Consider adding the directory checking in the script, and create one if the directory doesn't exist as part of process.

**Comment by viviant100** [comment]
> Unsure about configuring Standalone Harvest according to https://nasa-pds.github.io/registry/user/harvest_job_configuration.html#registry-integration. What file is this for?
> 
> UPDATE: after skimming some of the other sections at https://nasa-pds.github.io/registry/, my guess is that these configurations are in `<harvest application root>/conf/examples/*xml`. However, should it be that the xml files under `examples` are edited or that those files are copied one level up (same level as the examples directory) and edited?

@tloubrieu-jpl could we go over the configuration at one of the tagups?

**Comment by jordanpadams** [comment]
PDS4 IM released. Cloud components pending.

**Comment by tloubrieu-jpl** [comment]
I published the updated API documentation on https://nasa-pds.github.io/pds-api/

**Comment by tloubrieu-jpl** [comment]
I also checked the box for the gamma deployment of the API , see https://pds.nasa.gov/api/search-en-gamma/1/swagger-ui/index.html 

@sjoshi-jpl will do the production deployment next week.

**Comment by jordanpadams** [comment]
Done! 🎉
