### ISSUE TITLE
B14.1 EN Deployment & Release

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#456]
## 💡 Description

Fri 5/24/24 - Fri 6/7/24

**_NOTE: The following will most likely require review from the team based on components for this build._**

- [x] **Discipline LDD Release** @csuh (waiting for https://github.com/NASA-PDS/operations/issues/460)
     - [x] Stage (internal wiki, dLDDReleaseProcedures-StageLDDRelease)
     - [x] Release (internal wiki, dLDDReleaseProcedures-ReleaseLDDs)
     - [x] Post Release (internal wiki, dLDDReleaseProcedures-PostReleaseUpdates) 

- [ ] **Deployment of Test Environment**
    - [ ] DOI Service @csuh
    - [ ] DOI UI @csuh
    - [ ] Registry
        - [ ] API @tloubrieu-jpl / @sjoshi-jpl
        - [ ] update API documentation @tloubrieu-jpl / @sjoshi-jpl
        - [ ] Registry Sweeper @tloubrieu-jpl / @sjoshi-jpl
        - [ ] Registry Manager @c-suh 
        - [ ] Standalone Harvest @csuh

- [ ] **Deployment of Operational Environment**
    - [ ] DOI Service @csuh
    - [ ] DOI UI @csuh
    - [ ] Registry
        - [ ] API @tloubrieu-jpl / @sjoshi-jpl
        - [ ] update API documentation @tloubrieu-jpl / @sjoshi-jpl
        - [ ] Registry Sweeper @tloubrieu-jpl / @sjoshi-jpl
        - [ ] Registry Manager @c-suh 
        - [ ] Standalone Harvest @csuh

- [x] **Webpage Updated** @csuh
    - [x] Include updates to all pages that list PDS4 Build Schedule to add 4 additional releases (e.g. [here](https://pds.nasa.gov/datastandards/about/))
    - [x] Update multiple pages for new documents
    - [x] Post and update symlink for WebHelp ALL after Steve generates and sends those files

- [x] **Released to the Public**

**Comment by jordanpadams** [comment]
📆 05/2024 status: DDR completed on 5/29. Deployment in work.

**Comment by nutjob4life** [comment]
Will work on the middle part of the to-do list in the description

**Comment by c-suh** [comment]
Checked in with Jordan and Thomas, and nothing from the middle section needs to be redeployed. Closing this ticket as complete.
