### ISSUE TITLE
B14.0 dLDD Build and I&T

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#459]
## 💡 Description

- [x] Send email notification to dLDD stewards one week prior to tag
- [x] Tag dLDDs for release
- [x] Send email to stewards for review
- [x] dLDD Review by Stewards 10/24/23-11/13/23
- [x] Ping LDD stewards with open PRs, merge upon request (11/13/23)

**Comment by jordanpadams** [comment]
📆 October status: dLDDs build for stewards. Awaiting review and merge.

**Comment by jordanpadams** [comment]
Done and release
