### ISSUE TITLE
B14.1 dLDD Build and I&T

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#460]
## 💡 Description

- [x] Send email notification to dLDD stewards one week prior to tag
- [x] Tag dLDDs for release
- [x] Send email to stewards for review
- [x] dLDD Review by Stewards 4/30/24-5/20/24
- [x] Follow up with DD Stewards for any open PRs, and merge for them upon request (5/20/24-5/21/24)

**Comment by jordanpadams** [comment]
📆 05/2024 status: In work. On schedule.

**Comment by jordanpadams** [comment]
Stand-up Status: In work. Notification sent out again today. Numerous apps opened.
